version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    volumes:
      - .:/var/www
    ports:
      - "8084:80"  
    environment:
      DATABASE_URL: "mysql://root:root@database:3306/myBank?charset=utf8mb4"
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myBank                
      MYSQL_PASSWORD: root  
    ports:
      - "3308:3306" 
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
